blank_issues_enabled: false
contact_links:
  - name: Question or idea
    url: https://github.com/saianthireddy/ai-doctor/discussions
    about: Use Discussions for questions, ideas and show-and-tell.
